name: Check Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:

jobs:
  check-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Generate badges for submodules
        run: |
          # Create array of submodules to process
          SUBMODULES=("brother-ql-web" "ytdlp2strm" "mcp-grocy-api")
          
          # Process each submodule
          for submodule in "${SUBMODULES[@]}"; do
            # Get status of the submodule
            STATUS=$(git submodule status -- $submodule | awk '{print $1}')
            
            # Create badge name based on submodule name
            BADGE_NAME="${submodule}-status"
            
            # Use the BYOB API to create/update badge
            curl -X POST https://byob.yarr.is/api/badge \
              -H "Content-Type: application/json" \
              -d "{
                \"name\": \"${BADGE_NAME}\",
                \"icon\": \"octicon:git-branch-16\",
                \"status\": \"${submodule}: ${STATUS}\",
                \"color\": \"blue\",
                \"repository\": \"${{ github.repository }}\"
              }" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
            
            echo "Created/updated badge for ${submodule} with status ${STATUS}"
          done
